pipeline {
    agent any

    environment {
        BUILD_DIR  = "out/Release"
        PATH       = "D:/Code/msys64/mingw64/bin;${env.PATH}"
    }

    stages {
        stage('Configure') {
            steps {
                bat """
                    cmake -S . -B %BUILD_DIR% ^
                          -DCMAKE_BUILD_TYPE=Release ^
                          -G Ninja
                """
            }
        }

        stage('Build') {
            steps {
                bat 'cmake --build %BUILD_DIR% --parallel'
            }
        }

        stage('Test') {
            steps {
                bat 'cd %BUILD_DIR% && ctest --output-on-failure --output-junit ctest_results.xml'
            }
        }

        stage('Benchmark') {
            steps {
                bat '%BUILD_DIR%\\bench\\textops_bench.exe'
            }
        }
    }

    post {
        always {
            junit 'out/Release/ctest_results.xml'
        }
        success { echo 'Build passed!' }
        failure { echo 'Build failed!' }
    }
}